---
services:
  consul:
    image: hashicorp/consul:1.22
    command: [
      "agent",
      "-dev",
      "-client=0.0.0.0",
      "-ui"
    ]
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    volumes:
      - db-data:/consul/data
    restart: unless-stopped

volumes:
  db-data: {}
